### ISSUE TITLE
Package name mismatch

### ISSUE THREAD

**Issue by chicgeek** [holography/holograph-webpack-plugin#1]
Readme points to a non-existing package:
https://www.npmjs.com/package/holograph-webpack-plugin

The following package does exist, but also points to a repo on your personal account.
https://www.npmjs.com/package/hologram-webpack-plugin

    yarn add holograph-webpack-plugin
    error Couldn't find package "holograph-webpack-plugin" on the "npm" registry.

**Comment by blongden** [comment]
Strange. I'm sure it was there... anyway - republished it and the first link now works. The second link is for the hologram fork that Brian was working on (though I think is abandonded now).
